# Generated by Django 6.0.6 on 2026-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('jersey_type', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('has_custom_name', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
