# Generated by Django 6.0.6 on 2026-06-10 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('home', 'Home Kit'), ('away', 'Away Kit'), ('training', 'Training Kit')], default='home', max_length=20)),
                ('version', models.CharField(default='Player Edition', max_length=50)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jersey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jerseys.jersey')),
            ],
        ),
        migrations.CreateModel(
            name='JerseySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('jersey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='jerseys.jersey')),
            ],
            options={
                'unique_together': {('jersey', 'size')},
            },
        ),
    ]
